### ISSUE TITLE
How to get ground truth of dataset

### ISSUE THREAD

**Issue by zhanghanduo** [hisiter97/Object-Corner-Detection#1]
Hi. Thanks for the sharing!
Just wanna ask how to generate customized dataset? What I understand is making the 4 corners of a license plate into 4 tiny "bounding boxes", each with 4 pixel radius, and I label all of them a class "corner". Is that correct?

**Comment by hisiter97** [comment]
that's right, as long as centers of 4 boxes near corners of the license plate

**Comment by zhanghanduo** [comment]
This seems a dummy question, but what if I just label the whole plate as a bounding box? In my understanding, the features in the whole plate are more "abundant" than just a small area of keypoint.  In addition, you have to assign 4 points into a plate, which might bring additional assignment errors (in a crowd case).

**Comment by hisiter97** [comment]
In crowd case, you can detect vehicles before detect 4 points. That will improve accuracy
